on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Build Tennis Backend
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.17" # The Go version to download (if necessary) and use.
      
      - name: Build
        run: |
          cd backend
          go version
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o tennis-tournament-finder-backend main.go
          pwd
          ls -la
      
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "backend/tennis-tournament-finder-backend"
          target: ${{ secrets.DEPLOYMENT_PATH }}